version: "3.5"

services:
  app:
    image: "literal"
    container_name: "literal_app"
    build: literal
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
        - variables/dev.env
    volumes:
      - ./literal/:/app/
      - static_volume:/app/static
      - media_volume:/app/mediafiles

  postgres:
    image: postgres:12.0-alpine
    container_name: "literal_postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - ./variables/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: nginx
    container_name: "literal_nginx"
    ports:
      - 1337:80
    depends_on:
      - app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

volumes:
  postgres_data:
  static_volume:
  media_volume:
