version: "3.5"

services:
  app:
    image: "literal"
    container_name: "literal_app"
    build: literal
    volumes:
      - ./literal/:/app/
    command: gunicorn literal.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
        - variables/dev.env

  postgres:
    image: postgres:12.0-alpine
    container_name: "literal_postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - ./variables/dev.env

  nginx:
    build: nginx
    container_name: "literal_nginx"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
