# Generated by Django 3.2.2 on 2021-05-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="files/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Processing", "Processing"),
                            ("Sent", "Sent"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Active",
                        max_length=30,
                    ),
                ),
                ("text", models.TextField(null=True)),
                (
                    "userprofile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="authentication.userprofile",
                    ),
                ),
            ],
        ),
    ]
