# Generated by Django 3.2.2 on 2021-05-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_auto_20210518_0304"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="language",
        ),
    ]
