name: Literal CI/CD

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: |
          make start

  linting:
    name: Linting
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pylint
        run: |
          make pylint
      - name: Mypy
        run: |
          make mypy
      - name: Black
        run: |
          make black

  testing:
    name: Testing
    runs-on: ubuntu-20.04
    needs: [build, linting]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          make test

  push_to_registry_image:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [build, linting, testing]
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./literal
          file: ./literal/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/literal:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
