name: Literal CI/CD

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: |
          make start

  linting:
    name: Linting
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pylint
        run: |
          make pylint
      - name: Mypy
        run: |
          make mypy
      - name: Black
        run: |
          make black

  testing:
    name: Testing
    runs-on: ubuntu-20.04
    needs: [build, linting]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          make test
