name: Django CI/CD

on: [push]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./docker-compose.yaml
      - name: Build images
        run: |
          make start
