name: Django CI/CD

on: [push, pull_request]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: |
          make start

  linting:
    name: Linting
    runs-on: [self-hosted, docker]
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pylint
        run: |
          make pylint
      - name: Mypy
        run: |
          make mypy
      - name: Black
        run: |
          make black

  testing:
    name: Testing
    runs-on: [self-hosted, docker]
    needs: [build, linting]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test coverage
        run: |
          make test-coverage